name: str
industry_tags: list
address: dict
address.address2: str
address.street: str
address.city: str
address.region: str
address.postal_code: str
address.country: str
address.county: str
web_url: str
image_url: str
business_description: str
twitter: str
facebook: str
linkedin: str
instagram: str
naics_tag: str
legal_structure: str
contact_email: str
company_contact_email: str
company_contact_name: str
company_contact_title: str
phone: str
num_employees: bson.int64.Int64
executives: list
latitude: bson.int64.Int64
longitude: bson.int64.Int64
factual_id: NoneType
metadata: dict
metadata.search: str
minority_owned: bool
women_owned: bool
veteran_owned: bool
aliases: list
created_by: str
created: bson.int64.Int64
domain_name: str
updated: bson.int64.Int64
updated_by: str
claimed_client: str
is_test_company: bson.int64.Int64
country_code: NoneType
linkedin_id: NoneType
crunchbase_permalink: NoneType
woman_owned: str
failed_tags: list
naics: str
comments: str
description_headline: str
